//go:build ignore

package main

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	paths := []string{
		filepath.Join("..", "..", "target", "release", "libgusset.a"),
		filepath.Join("..", "..", "target", "debug", "libgusset.a"),
	}

	var data []byte
	var err error
	for _, p := range paths {
		data, err = os.ReadFile(p)
		if err == nil {
			break
		}
	}

	hashStr := "no-archive-found"
	if len(data) > 0 {
		hashStr = fmt.Sprintf("%x", sha256.Sum256(data))
	}

	content := fmt.Sprintf(`package ffi

// Code generated by go generate; DO NOT EDIT.

const ArchiveHash = %q
`, hashStr)

	if err := os.WriteFile("archive_hash.go", []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write archive_hash.go: %v\n", err)
		os.Exit(1)
	}
}
