[workspace]
members = [
    "crates/gusset",
    "crates/gusset-example",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
authors = ["Bharath Chandra"]

[profile.dev]
panic = "unwind"
overflow-checks = true

[profile.release]
panic = "unwind"
codegen-units = 1
lto = "fat"
opt-level = 3
